const LOAD_MESSAGES = 'LOAD_MESSAGES'
const CREATE_MESSAGE = 'CREATE_MESSAGE'

const LOAD_ROOM = 'LOAD_ROOM'

const LOAD_ROOMUSERS = 'LOAD_ROOMUSERS'
const ADD_ROOMUSER = 'ADD_ROOMUSER'

const UPDATE_USERROOM = 'UPDATE_USERROOM'
const UPDATE_USERLOC = 'UPDATE_USERLOC'

const INITIALIZE_USER = 'INITIALIZE_USER'

export {LOAD_MESSAGES, CREATE_MESSAGE, LOAD_ROOM, LOAD_ROOMUSERS, UPDATE_USERROOM, ADD_ROOMUSER, UPDATE_USERLOC, INITIALIZE_USER}
