const LOAD_MESSAGES = 'LOAD_MESSAGES'
const CREATE_MESSAGE = 'CREATE_MESSAGE'
const LOAD_RESTAURANTS = 'LOAD_RESTAURANTS'
const CREATE_RESTAURANT = 'CREATE_RESTAURANT'

export {LOAD_MESSAGES, CREATE_MESSAGE, LOAD_RESTAURANTS, CREATE_RESTAURANT}
